In [1]:
%pip install duckdb

Requirement already satisfied: duckdb in /opt/conda/lib/python3.11/site-packages (1.5.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import duckdb

con = duckdb.connect("../duckdb/lakehouse.duckdb")

In [4]:
con.sql("""
SELECT table_schema, table_name
FROM information_schema.tables
ORDER BY 1,2
""").df()

  table_schema                           table_name
0       bronze      despesas_funcional_programatica
1       bronze                   despesas_por_orgao
2         ouro      despesas_funcional_programatica
3         ouro                   despesas_por_orgao
4        prata  stg_despesas_funcional_programatica
5        prata               stg_despesas_por_orgao

In [5]:
df = con.sql("""
SELECT *
FROM prata.stg_despesas_por_orgao
""").df()

In [6]:
df

,ano,codigo_orgao,codigo_orgao_superior,nome_orgao,nome_orgao_superior,pacote,valor_empenhado,valor_liquidado,valor_pago,fl_ano_eleitoral,tipo_eleicao,__ingestion_id,ingestion_time,__source,__endpoint
0,2026,30108,30000,Polícia Federal,Ministério da Justiça e Segurança Pública,coordenacao_politica,5.703745e+09,3.904236e+09,3.579438e+09,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
1,2026,30802,30000,Polícia Rodoviária Federal,Ministério da Justiça e Segurança Pública,coordenacao_politica,6.624028e+09,2.676313e+09,2.468725e+09,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
2,2026,30000,30000,Ministério da Justiça e Segurança Pública - Un...,Ministério da Justiça e Segurança Pública,coordenacao_politica,1.069376e+09,3.052266e+08,2.962824e+08,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
3,2026,30911,30000,Fundo Nacional de Segurança Pública,Ministério da Justiça e Segurança Pública,coordenacao_politica,2.024279e+09,2.823155e+08,2.762398e+08,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
4,2026,30907,30000,Fundo Penitenciário Nacional,Ministério da Justiça e Segurança Pública,coordenacao_politica,2.741341e+08,5.092918e+07,5.030894e+07,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2363,2014,36201,36000,Fundação Oswaldo Cruz,Ministério da Saúde,nucleo_eleitoral,4.223811e+09,3.424827e+09,3.282154e+09,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
2364,2014,36211,36000,Fundação Nacional de Saúde,Ministério da Saúde,nucleo_eleitoral,3.412043e+09,2.771564e+09,2.765220e+09,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
2365,2014,36210,36000,Hospital Nossa Senhora da Conceição S.A.,Ministério da Saúde,nucleo_eleitoral,1.154951e+09,1.137548e+09,1.117509e+09,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
2366,2014,36212,36000,Agência Nacional de Vigilância Sanitária,Ministério da Saúde,nucleo_eleitoral,6.623211e+08,6.214718e+08,6.214606e+08,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao
2367,2014,36213,36000,Agência Nacional de Saúde Suplementar,Ministério da Saúde,nucleo_eleitoral,2.762773e+08,2.521865e+08,2.521865e+08,True,geral,489dcaa2-55c4-4ef9-8be0-fa650779bc70,2026-06-08 01:46:17.166886,Portal da Transparencia,/api-de-dados/despesas/por-orgao